### ISSUE TITLE
tests run repeatedly when using --json --outputFile flags

### ISSUE THREAD

**Issue by indefinitelee** [guestlinelabs/jest-run#1]
`jest-run --env=jsdom` works as expected, when the test fails it exits and shows 3 passing tests 1 failed test.  

when I add the output flags like so: 
`jest-run --env=jsdom --json --outputFile=./src/__tests__/results/testResults.jsontestResults.json`

it just keeps rerunning the failed test. output is going to the specified folder which is in my excluded paths array ` "testPathIgnorePatterns": [      "<rootDir>/src/__tests__/results/"`

**Comment by fbarbare** [comment]
HI @indefinitelee ,

You are running Jest in watch mode: refer to this to learn more - https://github.com/guestlinelabs/jest-run#watch-mode
Because you are using the watch mode, and at the same time save a file that is in the scope of the watch mode, it will keep re-running the tests.

If you want to write reports for a CI/CD pipeline, use the `CI=true` variable.

Closing the issue for now, if you still have problems, feel free to reopen it with more details :)
